### ISSUE TITLE
No Issues

### ISSUE THREAD

**Issue by brokenbadger** [Hagtronics/SDRpp-FrequencyManager-Spreadsheet-Tool#1]
Just wanted to express my thanks for creating this. Just what I was looking for.
This solution not only does what I wanted but gives me loads more flexibility than other options.
Much appreciated.

**Comment by Hagtronics** [comment]
Thank you for the kind comment. As they say: "Necessity is the mother of invention", as I needed this for myself too!  Take care and happy DXing!  :-)
